{
 "title": "Powerdns recursor",
 "description": "Powerdns recursor - https://www.powerdns.com/powerdns-recursor",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(pdns_recursor_questions,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Question/s vs answer/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(pdns_recursor_questions{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "queries"
    },
    {
     "expr": "sum(rate(pdns_recursor_servfail_answers{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "answers - servfail"
    },
    {
     "expr": "sum(rate(pdns_recursor_nxdomain_answers{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "answers - nxdomain"
    },
    {
     "expr": "sum(rate(pdns_recursor_noerror_answers{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "answers - noerror"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "pdns_recursor_qa_latency{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Time to answer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(pdns_recursor_answers0_1{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "<1ms"
    },
    {
     "expr": "sum(rate(pdns_recursor_answers1_10{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "1ms-10ms"
    },
    {
     "expr": "sum(rate(pdns_recursor_answers10_100{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "10ms-100ms"
    },
    {
     "expr": "sum(rate(pdns_recursor_answers100_1000{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "100ms-1s"
    },
    {
     "expr": "sum(rate(pdns_recursor_answers_slow{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": ">1s"
    }
   ]
  },
  {
   "title": "Questions errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(pdns_recursor_unauthorized_tcp{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "unauthorized tcp"
    },
    {
     "expr": "sum(rate(pdns_recursor_unauthorized_udp{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "unauthorized udp"
    },
    {
     "expr": "sum(rate(pdns_recursor_truncated_drops{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "truncated"
    },
    {
     "expr": "sum(rate(pdns_recursor_too_old_drops{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "too old"
    },
    {
     "expr": "sum(rate(pdns_recursor_query_pipe_full_drops{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "pipe full"
    },
    {
     "expr": "sum(rate(pdns_recursor_over_capacity_drops{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "maximum concurrent query"
    }
   ]
  },
  {
   "title": "Packet cache hits vs misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(pdns_recursor_packetcache_hits{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "hits"
    },
    {
     "expr": "sum(rate(pdns_recursor_packetcache_misses{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Packet cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(pdns_recursor_packetcache_entries{instance=~\"$instance\"})",
     "legendFormat": "entries"
    }
   ]
  },
  {
   "title": "Cache hits vs misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(pdns_recursor_cache_hits{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "hits"
    },
    {
     "expr": "sum(rate(pdns_recursor_cache_misses{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(pdns_recursor_cache_entries{instance=~\"$instance\"})",
     "legendFormat": "entries"
    },
    {
     "expr": "sum(pdns_recursor_negcache_entries{instance=~\"$instance\"})",
     "legendFormat": "negcache"
    }
   ]
  },
  {
   "title": "Queries protocol usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(pdns_recursor_tcp_questions{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "TCP"
    },
    {
     "expr": "sum(rate(pdns_recursor_questions{instance=~\"$instance\"}[$__rate_interval])) - sum(rate(pdns_recursor_tcp_questions{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "UDP"
    }
   ]
  },
  {
   "title": "UDP errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(pdns_recursor_udp_in_csum_errors{instance=~\"$instance\"}[$__rate_interval])) + sum(rate(pdns_recursor_udp6_in_csum_errors{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "in checksum"
    },
    {
     "expr": "sum(rate(pdns_recursor_udp_in_errors{instance=~\"$instance\"}[$__rate_interval])) + sum(rate(pdns_recursor_udp6_in_errors{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "in"
    },
    {
     "expr": "sum(rate(pdns_recursor_udp_noport_errors{instance=~\"$instance\"}[$__rate_interval])) + sum(rate(pdns_recursor_udp6_noport_errors{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "noport"
    },
    {
     "expr": "sum(rate(pdns_recursor_udp_recvbuf_errors{instance=~\"$instance\"}[$__rate_interval])) + sum(rate(pdns_recursor_udp6_recvbuf_errors{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "recvbuf"
    },
    {
     "expr": "sum(rate(pdns_recursor_udp_sndbuf_errors{instance=~\"$instance\"}[$__rate_interval])) + sum(rate(pdns_recursor_udp6_sndbuf_errors{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "sndbuf"
    }
   ]
  },
  {
   "title": "RPZ packets response",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(pdns_recursor_policy_result_custom{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "custom"
    },
    {
     "expr": "sum(rate(pdns_recursor_policy_result_drop{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "drop"
    },
    {
     "expr": "sum(rate(pdns_recursor_policy_result_noaction{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "noaction"
    },
    {
     "expr": "sum(rate(pdns_recursor_policy_result_nodata{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "nodata"
    },
    {
     "expr": "sum(rate(pdns_recursor_policy_result_nxdomain{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "nxdomain"
    },
    {
     "expr": "sum(rate(pdns_recursor_policy_result_truncate{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "truncate"
    }
   ]
  }
 ]
}