{
 "title": "Routinator2",
 "description": "This dashboard provides trust anchor and repository statistics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(routinator_repository_publication_points_total,instance)"
    }
   },
   {
    "name": "repo",
    "query": "routinator_repository_publication_points_total"
   }
  ]
 },
 "panels": [
  { "title": "Repository Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Route Origin Attestations (ROAs)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "routinator_repository_objects_total{instance=\"$instance\", uri=\"$repo\", type=\"roa\", state=\"valid\"}",
     "legendFormat": "Valid"
    },
    {
     "expr": "routinator_repository_objects_total{instance=\"$instance\", uri=\"$repo\", type=\"roa\", state=\"invalid\"}",
     "legendFormat": "Invalid"
    }
   ]
  },
  {
   "title": "Validated ROA Payloads (VRPs)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "routinator_repository_contributed_vrps_total{instance=\"$instance\", uri=\"$repo\"}",
     "legendFormat": "Contributed (Valid minus Excluded)"
    }
   ]
  },
  {
   "title": "Valid Publication Points",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "routinator_repository_publication_points_total{instance=\"$instance\", uri=\"$repo\", state=\"valid\"}",
     "legendFormat": "Valid Publication Points"
    },
    {
     "expr": "routinator_repository_objects_total{instance=\"$instance\", uri=\"$repo\", type=\"manifest\", state=\"valid\"}",
     "legendFormat": "Valid Manifests"
    },
    {
     "expr": "routinator_repository_objects_total{instance=\"$instance\", uri=\"$repo\", type=\"crl\", state=\"valid\"}",
     "legendFormat": "Valid Manifests"
    }
   ]
  },
  {
   "title": "CA Certificates",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "routinator_repository_objects_total{instance=\"$instance\", uri=\"$repo\", type=\"ca_cert\", state=\"valid\"}",
     "legendFormat": "CA Certificates"
    }
   ]
  },
  {
   "title": "Excluded VRPs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "routinator_repository_duplicate_vrps_total{instance=\"$instance\", uri=\"$repo\"}",
     "legendFormat": "Duplicate"
    },
    {
     "expr": "routinator_repository_locally_filtered_vrps_total{instance=\"$instance\", uri=\"$repo\"}",
     "legendFormat": "Locally Filtered"
    },
    {
     "expr": "routinator_repository_unsafe_vrps_total{instance=\"$instance\", uri=\"$repo\"}",
     "legendFormat": "Unsafe"
    }
   ]
  },
  {
   "title": "Rejected Publication Points",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "routinator_repository_publication_points_total{instance=\"$instance\", uri=\"$repo\", state=\"rejected\"}",
     "legendFormat": "Rejected Publication Points"
    },
    {
     "expr": "routinator_repository_objects_total{instance=\"$instance\", uri=\"$repo\", type=\"manifest\", state=\"stale\"}",
     "legendFormat": "Stale Manifests"
    },
    {
     "expr": "routinator_repository_objects_total{instance=\"$instance\", uri=\"$repo\", type=\"crl\", state=\"invalid\"}",
     "legendFormat": "Invalid CRLs"
    }
   ]
  },
  {
   "title": "Update Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "routinator_rrdp_duration{instance=\"$instance\", uri=\"$repo\"}",
     "legendFormat": "RRDP"
    }
   ]
  },
  {
   "title": "Connection Status",
   "type": "timeseries",
   "description": "RDP status code : 0 = Success, 10 = Error in socket I/O, 35 = Timeout waiting for daemon connection\nRsync status code : 200 = OK, 304 = Not Modified, 503 = Service Unavailable",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "routinator_rrdp_status{instance=\"$instance\", uri=\"$repo\"}",
     "legendFormat": "RRDP status code"
    }
   ]
  },
  { "title": "Trust Anchor Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "RIPE NCC VRPs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "routinator_ta_valid_vrps_total{instance=\"$instance\", name=\"ripe\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "APNIC VRPs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "routinator_ta_valid_vrps_total{instance=\"$instance\", name=\"apnic\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last update duration",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "routinator_last_update_duration{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RIPE NCC VRPs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "routinator_ta_valid_vrps_total{instance=\"$instance\", name=\"arin\"}",
     "legendFormat": "ARIN"
    }
   ]
  },
  {
   "title": "LACNIC VRPs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "routinator_ta_valid_vrps_total{instance=\"$instance\", name=\"lacnic\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RTR Serial",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "routinator_serial{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AFRINIC VRPs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "routinator_ta_valid_vrps_total{instance=\"$instance\", name=\"afrinic\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All VRPs (logarithmic scale)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "routinator_ta_valid_vrps_total{instance=\"$instance\", name=\"ripe\"}",
     "legendFormat": "RIPE NCC"
    },
    {
     "expr": "routinator_ta_valid_vrps_total{instance=\"$instance\", name=\"apnic\"}",
     "legendFormat": "APNIC"
    },
    {
     "expr": "routinator_ta_valid_vrps_total{instance=\"$instance\", name=\"lacnic\"}",
     "legendFormat": "LACNIC"
    },
    {
     "expr": "routinator_ta_valid_vrps_total{instance=\"$instance\", name=\"arin\"}",
     "legendFormat": "ARIN"
    },
    {
     "expr": "routinator_ta_valid_vrps_total{instance=\"$instance\", name=\"afrinic\"}",
     "legendFormat": "AFRINIC"
    }
   ]
  },
  {
   "title": "Total Validation Run Duration vs. RRDP or Rsync Update Time of Each Repo",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "routinator_rsync_duration{instance=\"$instance\"}",
     "legendFormat": "{{uri}}"
    },
    {
     "expr": "routinator_rrdp_duration{instance=\"$instance\"}",
     "legendFormat": "{{uri}}"
    },
    {
     "expr": "routinator_last_update_duration{instance=\"$instance\"}",
     "legendFormat": "Total Time to Fetch Data + Cryptographic Validation"
    }
   ]
  },
  {
   "title": "rsync exit code (0 = Success, 10 = Error in socket I/O, 35 = Timeout waiting for daemon connection)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "routinator_rsync_status{instance=\"$instance\"}",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "RRDP exit code (200 = Success, -1 = Cannot Connect)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "routinator_rrdp_status{instance=\"$instance\"}",
     "legendFormat": "{{uri}}"
    }
   ]
  }
 ]
}